### ISSUE TITLE
The app closes on starting the download

### ISSUE THREAD

**Issue by pro-beginner** [kshitij1234/Anime-Downloader#2]
I am trying to use the app on mac os 10.12 and here is the issue I am facing:
When I click the "Start Download" button on the GUI the app shuts down and my eclipse shows the following error on running the Main.java file and starting the download..
`java.io.IOException: Cannot run program ""python"": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at application.view.animeheaven.AnimeHeavenController$1.run(AnimeHeavenController.java:106)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more`

**Comment by kshitij1234** [comment]
Have you installed python on your system? The error is caused because your system cannot recognize the command python (filename). Confirm that. There might also be the problem of python version so try changing python to python3 in AnimeHeavenController.java:106.

**Comment by pro-beginner** [comment]
Done that.. have python 3.6 installed still the java gui still closes on
starting download.
Also we tried to use the AnimeDownloader.py directly, in that the
requests.get(downlink) part is taking a lot of time, is that ok. ?? Further
on doing  " curl downlink --output <f_name> " the downlaod starts.

**Comment by kshitij1234** [comment]
Actually I have only tested the software on Windows and it was working fine a few days back. I cannot check right now due to slow internet. The requests.get() part should normally take about 5 seconds with a decent internet connection. You say the script is working fine when you run it from the terminal?
Another anomaly I detected a few days back was that the animeheaven.eu developers have built some kind of IP limiting which does not allow more than about 30 downloads in one day. Maybe this is what causes the shutdown (if you have used up that limit). I will work on it once I get to a good internet source(maybe next week).
